name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: run bulid
      run: cargo build --release
    - name: upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mcreator-tookit-rust
        path: '**/target/*.exe'
